SET OSGEO4W_ROOT=C:\OSGeo4W64
sET QGISNAME=qgis
SET QGIS=%OSGEO4W_ROOT%\apps\%QGISNAME%
SET QGIS_PREFIX_PATH=%QGIS%

CALL %OSGEO4W_ROOT%\bin\O4w_env.bat

SET PATH=%PATH%;%QGIS%\bin
SET PYTHONPATH=%QGIS!\python;%PYTHONPATH%

start /wait 1_EPRiMA_PROJECTION.EXE
start /wait 2_EPRiMA_Normalization.EXE
start /wait 3_EPRiMA_TCI_MUNI.EXE
start /wait 4_EPRiMA_VCI_MUNI.EXE
start /wait 5_EPRiMA_W30_VHI.EXE%*
start /wait 6_EPRiMA_JSON_RICE_MEAN_VHI_uVHI.EXE


